name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build and deploy
        run: |
          npm run build
          echo "Deploying to GitHub Pages..."
          git config --local user.email "YUnastasiyka@github.com"
          git config --local user.name "yu_anastasiia"
          git checkout gh-pages || git checkout --orphan gh-pages
          git rm -rf .
          mv dist/* .
          rm -R dist
          git add -A
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages

      - name: Run image and script
        run: |
          docker run your-docker-image
          bash your-script.sh
